#!/usr/bin/awk -f

# This AWK script counts the number of lines generated by rWasm and number of
# lines generated by the LLM. Note that it assumes the LLM lines are wrapped in
# the "LLM Output" comment block so ensure that before running this script.

BEGIN {
  RWASM=0;
  LLM=0;
  IS_LLM_LINES=0;
}

# If LLM marker is met, then toggle the LLM flag.
/^.* LLM Output .*$/ {
  IS_LLM_LINES=!IS_LLM_LINES;
}

# For every line, increment the LLM line counter or the RWASM line counter.
{
  if ( IS_LLM_LINES ) {
    LLM++;
  } else {
    RWASM++;
  }
}

# print the result at the end
END {
  print LLM "," RWASM
}

