
[package]
name = "c_transcoder_modular_exponentiation_power_in_modular_arithmetic_out-rwasm-mutated"
version = "1.0.1"
authors = ["generated-by-rwasm-1.0.1"]
edition = "2018"

[dependencies]
wasi-common = "0.20.0"
wiggle = "0.20.0"


            