[package]
name = "brotli_parseint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[test]]
name = "brotli_parseint_test"
harness = false

[dev-dependencies]
bolero = "0.9.0"
